default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: esport-digest_development
test:
  <<: *default
  database:  esport-digest_test<%= ENV['TEST_ENV_NUMBER'] %>
production:
  <<: *default
  database: esport-digest_prod