default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: same-chances_development
test:
  <<: *default
  database:  same-chances_test<%= ENV['TEST_ENV_NUMBER'] %>
  port: 5432
  host: 127.0.0.1
production:
  <<: *default
  database: same-chances_prod
